import {ArrowDown,ArrowUpRight,ChartCandlestick,Search,ShieldCheck,Command,Workflow,Wallet} from 'lucide-react';
import {WalletAccount} from '@/components/wallet-account';
import {Downloads} from '@/components/downloads';
import {authConfigured} from '@/lib/config';
export const dynamic='force-dynamic';
export default function Home(){return <>
  <header className="site-nav"><a href="/" className="brand"><span className="brand-mark">c</span>clawd<span className="brand-divider"/>DESKTOP</a><nav aria-label="Main navigation"><a href="#workspace">Workspace</a><a href="#access">Access</a><a href="#download">Download</a><a href="/mobile">Mobile</a></nav><WalletAccount enabled={authConfigured()}/></header>
  <main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/>BUILT FOR SOLANA. AT HOME ON YOUR DESKTOP.</div><h1>Your market.<br/>Your agents.<br/><span>Your desk.</span></h1><p>A native workspace for researching tokens, following the market, and working with AI. Bring the conversation, charts, and tools together.</p><div className="hero-actions"><a className="button primary" href="#download">Get Clawd <ArrowDown size={16}/></a><a className="text-button" href="#workspace">Explore the workspace <ArrowUpRight size={15}/></a></div><div className="hero-footnote"><Command size={13}/> Native desktop · Solana wallet identity · Your workflow</div></div>
      <div className="desk-preview" aria-label="Clawd research workflow illustration"><div className="window-bar"><span/><span/><span/><div>CLAWD / RESEARCH DESK</div><span className="preview-label">WORKFLOW</span></div><div className="preview-body"><aside><div className="desk-name"><span className="brand-mark">c</span>clawd</div><p><Search size={13}/>Research</p><p><ChartCandlestick size={13}/>Markets</p><p><Workflow size={13}/>Routines</p><div className="sidebar-bottom">ONE WORKSPACE.<br/>YOUR CONTEXT.</div></aside><div className="preview-content"><div className="preview-prompt">Research SOL. Show the chart.<br/>Explain what changed.</div><div className="preview-step"><span>01</span><div><strong>Resolve the asset</strong><p>Exact network and token address.</p></div><ShieldCheck size={15}/></div><div className="preview-step"><span>02</span><div><strong>Bring in the evidence</strong><p>Price, candles, liquidity, sources, timestamps.</p></div><ChartCandlestick size={15}/></div><div className="preview-step"><span>03</span><div><strong>Keep the context</strong><p>Ask a follow-up. Inspect the chart.</p></div><Search size={15}/></div><div className="preview-composer">What would you like to understand?<span>↵</span></div></div></div><div className="window-footer"><span className="status-dot"/>RESEARCH → CONTEXT → DECISION<span>YOU STAY IN CONTROL</span></div></div>
    </section>
    <section className="workspace-section" id="workspace"><div className="section-heading"><span className="eyebrow">THE CLAWD WORKSPACE</span><h2>Follow the question.<br/>Keep the whole picture.</h2><p>Move from a ticker to its market, from a source to a clear answer, and from a repeated task to a routine.</p></div><div className="feature-grid">{[
      {icon:Search,title:'Search inside the conversation',text:'Research the web and keep the sources with the conversation. Follow-up questions can use the evidence you already gathered.'},
      {icon:ChartCandlestick,title:'Charts with context',text:'Inspect real candles, liquidity, volume, and token fundamentals. Keep the source, pool, and retrieval time visible.'},
      {icon:Workflow,title:'Agents that work with you',text:'Give agents a role, build a team, and create routines around your research workflow. Review actions that need your approval.'},
      {icon:Wallet,title:'A wallet you control',text:'Use a Solana wallet for your website identity. Payments and transaction approvals stay explicit in your wallet.'},
    ].map(({icon:Icon,title,text})=><article className="feature" key={title}><Icon size={21}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="access-section" id="access"><div><span className="eyebrow">ONE ACCOUNT, YOUR DESK</span><h2>Start with your wallet.<br/>Build your workflow.</h2><p>Wallet signup, subscriptions, and service access are being connected to one Clawd account. Paid access will show the exact asset, recipient, price, and term before you approve.</p><WalletAccount enabled={authConfigured()}/></div><div className="access-ledger"><div><span>IDENTITY</span><strong>Solana wallet</strong></div><div><span>PAYMENTS</span><strong>Solana + x402</strong></div><div><span>PLAN</span><strong>Launch pricing pending</strong></div><p>No payment is requested until checkout is configured and verified.</p></div></section>
    <section className="download-section" id="download"><div className="section-heading"><span className="eyebrow">MAKE IT YOUR DESKTOP</span><h2>A home for your<br/>Solana workflow.</h2><p>Choose Mac, Windows, or Linux. Release downloads include a version, checksum, and verified signing status.</p></div><Downloads/></section>
  </main><footer><a className="brand" href="/"><span className="brand-mark">c</span>clawd</a><p>Your Solana desktop.</p><a href="/privacy">Privacy & download measurement <ArrowUpRight size={13}/></a></footer>
</>;}
